config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users
  as :user do
    get "signin", to: 'devise/sessions#new'
    delete "signout", to: 'devise/sessions#destroy'
    get 'signup', to: 'devise/registrations#new'
  end

  get 'feed', to: 'feed#show'

  resources :users, only: :show, param: :username do
    member do
      post 'follow', to: 'follows#create'
      delete 'unfollow', to: 'follows#destroy'
    end
  end
  
  resources :mwo_builds do
    member do
      post 'vote', to: 'votes#create_upvote'
      post 'downvote', to: 'votes#create_downvote'
      delete 'unvote', to: 'votes#destroy_upvote'
      delete 'undownvote', to: 'votes#destroy_downvote'
    end
  end

  resources :builds do
    member do
      post 'vote', to: 'votes#create_upvote'
      post 'downvote', to: 'votes#create_downvote'
      delete 'unvote', to: 'votes#destroy_upvote'
      delete 'undownvote', to: 'votes#destroy_downvote'
    end
  end

  resources :tweets
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact-us', to: 'pages#contact_us'
  get 'builds', to: 'builds#index'
  get 'mwo_builds', to: 'mwo_builds#index'
  get 'feed', to: 'feed#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  # GET /tweets
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  def show
    @tweet = Tweet.find(params[:id])
  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.new
  end

  # GET /tweets/1/edit
  def edit
    @tweet = current_user.tweets.find(params[:id])
  end

  # POST /tweets
  def create
    @tweet = current_user.tweets.new(tweet_params)
    if @tweet.save
      redirect_to @tweet, notice: 'Tweet was successfully created.'
    else
      render :new 
    end
  end

  # PATCH/PUT /tweets/1
  def update
    @tweet = current_user.tweets.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to @tweet, notice: 'Tweet was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tweets/1
  def destroy
    @tweet = current_user.tweets.find(params[:id])
    @tweet.destroy
    redirect_to tweets_url, notice: 'Tweet was successfully destroyed.'
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:content)
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, id: :tweet_content, class: "form-control" %>
  </div>

  <%= form.submit class: "btn btn-primary" %>
<% end %>

app/views/tweets/edit.html.erb
<div class="container">
	<h1>Editing Tweet</h1>

	<%= render 'form', tweet: @tweet %>

	<%= link_to 'Show', @tweet %> |
	<%= link_to 'Back', tweets_path %>
</div>

app/views/tweets/index.html.erb
<div class="container">

  <h1>Tweets</h1>

  <table class="table table-inverse">
    <thead>
      <tr>
        <th>Id</th>
        <th>User</th>
        <th>Content</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @tweets.each do |tweet| %>
        <tr>
          <td><%= tweet.id %></td>
          <td><%= tweet.user.email %></td>
          <td><%= tweet.content %></td>
          <td><%= link_to 'Show', tweet %></td>
          <% if tweet.user == current_user %>
            <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
            <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <% if user_signed_in? %>
    <%= link_to 'New Tweet', new_tweet_path %>
  <% end %>

</div>

app/views/tweets/new.html.erb
<div class="container">
	<h1>New Tweet</h1>

	<%= render 'form', tweet: @tweet %>

	<%= link_to 'Back', tweets_path %>
</div>

app/views/tweets/show.html.erb
<div class="container">
	<p>
	  <strong>User:</strong>
	  <%= @tweet.user %>
	</p>

	<p>
	  <strong>Content:</strong>
	  <%= @tweet.content %>
	</p>

	<% if @tweet.user == current_user %>
		<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
	<% end %>
	<%= link_to 'Back', tweets_path %>
</div>