config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users
  as :user do
    get "signin", to: 'devise/sessions#new'
    delete "signout", to: 'devise/sessions#destroy'
    get 'signup', to: 'devise/registrations#new'
  end

  get 'feed', to: 'feed#show'

  resources :users, only: :show, param: :username do
    member do
      post 'follow', to: 'follows#create'
      delete 'unfollow', to: 'follows#destroy'
    end
  end
  
  resources :mwo_builds do
    member do
      post 'vote', to: 'votes#create_upvote'
      post 'downvote', to: 'votes#create_downvote'
      delete 'unvote', to: 'votes#destroy_upvote'
      delete 'undownvote', to: 'votes#destroy_downvote'
    end
  end

  resources :builds do
    member do
      post 'vote', to: 'votes#create_upvote'
      post 'downvote', to: 'votes#create_downvote'
      delete 'unvote', to: 'votes#destroy_upvote'
      delete 'undownvote', to: 'votes#destroy_downvote'
    end
  end

  resources :tweets
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact-us', to: 'pages#contact_us'
  get 'builds', to: 'builds#index'
  get 'mwo_builds', to: 'mwo_builds#index'
  get 'feed', to: 'feed#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/build.rb
class Build < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  validates :user, presence: true
  validates :ship, presence: true
  validates :url, presence: true

  acts_as_votable
end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  # GET /builds
  def index
    @builds = Build.all
  end

  # GET /builds/1
  def show
    @build = Build.find(params[:id])
  end

  # GET /builds/new
  def new
    @build = current_user.builds.new
  end

  # GET /builds/1/edit
  def edit
     @build = current_user.builds.find(params[:id])
  end

  # POST /builds
  def create
    @build = current_user.builds.new(build_params)
    if @build.save
      redirect_to @build, notice: 'Build was successfully created.'
    else
      render :new 
    end
  end

  # PATCH/PUT /builds/1
  def update
    @build = current_user.builds.find(params[:id])
    if @build.update(build_params)
      redirect_to @build, notice: 'Build was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /builds/1
  def destroy
    @build = current_user.builds.find(params[:id])
    @build.destroy
    redirect_to builds_url, notice: 'Build was successfully destroyed.'
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def build_params
      params.require(:build).permit(:ship, :name, :url, :comments)
    end
end

app/helpers/builds_helper.rb
module BuildsHelper
end

app/views/builds/_form.html.erb
<%= form_with(model: build, local: true) do |form| %>
  <% if build.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(build.errors.count, "error") %> prohibited this build from being saved:</h2>

      <ul>
      <% build.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :build_name, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :ship %>
    <%= form.text_field :ship, id: :build_ship, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :url %>
    <%= form.text_field :url, id: :build_url, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :comments %>
    <%= form.text_area :comments, id: :build_comments, class: "form-control"  %>
  </div>

  <%= form.submit class: "btn btn-primary" %>
<% end %>

app/views/builds/edit.html.erb
<div class="container">	
	<h1>Editing Ship Build</h1>

	<%= render 'form', build: @build %>

	<%= link_to 'Show', @build %> |
	<%= link_to 'Back', builds_path %>
</div>

app/views/builds/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="card boarder-dark">
        <% if user_signed_in? %>
          <div class="card-body text-dark">
            <h4 class="card-title text-dark">Your Account</h4>
            <% if current_user.avatar.present? %>
              <center><%= image_tag current_user.avatar.url(:medium) %></center>
            <% end %>
            <p class="card-text"><%= current_user.username %></p>
            <p class="card-text"><%= current_user.email %></p>
          </div>
          <div class="card-footer text-primary">
            <a class="card-link"><%= link_to 'Edit your account', user_path(current_user.username) %></a>
          </div>
          <% else %>
          <h6 class="card-text text-dark"><%= link_to "Sign up", signup_path %></h6>
          <h6 class="card-text text-dark"><%= link_to "Sign in", signin_path %></h6>
        <% end %>
      </div>
    </div>
    <div class="col-md-8">  
      <h1>Elite Dangerous Ship Builds</h1>
      <% if user_signed_in? %>
        <%= link_to 'New Ship Build', new_build_path %>
      <% end %>
      <ul class="list-group">
        <% @builds.each do |build| %>
          <%= link_to build, class: "list-group-item list-group-item-action list-group-item-light" do %>
            <h5 class="list-group-item-heading text-dark"><strong> Submitted by:</strong> <%= build.user.username %></strong></h5>
            <p class="list-group-item-text text-dark""><strong>Build Name:</strong> <%= build.name %></p>
            <p class="list-group-item-text text-dark""><strong>Ship:</strong> <%= build.ship %></p>
            <p class="list-group-item-text text-dark""><strong>Comments:</strong> <%= build.comments %></p>
            <p class="list-group-item-text text-dark"">Likes: <%= build.get_upvotes.size %> | Dislikes: <%= build.get_downvotes.size %></p>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/builds/new.html.erb
<div class="container">	
	<h1>New Ship Build</h1>

	<%= render 'form', build: @build %>

	<%= link_to 'Back', builds_path %>
</div>

app/views/builds/show.html.erb
<div class="container">
  <div class="row">
    <div class="offset-md-2 col-md-8">
      <div class="card boarder-dark">
        <div class="card-body text-dark">
          <h4 class="card-title text-dark"><%= link_to @build.user.username, user_path(@build.user.username) %></h4>
            <p class="card-text"><strong>Build Name:</strong> <%= @build.name %></p>
            <p class="card-text"><strong>Ship:</strong> <%= @build.ship %></p>
            <p class="card-text"><strong>URL:</strong> <%= link_to(truncate(@build.url, :length => 140), @build.url, target: :_blank) %></p>
            <p class="card-text"><strong>Comments:</strong> <%= @build.comments %></p>
            <p class="card-text">Likes: <%= @build.get_upvotes.size %> | Dislikes: <%= @build.get_downvotes.size %></p>
        </div>
        <div class="card-footer text-primary">
          <%if @build.user == current_user %>
            <%= link_to 'Edit', edit_build_path(@build) %> |
            <%= link_to 'Delete', @build, method: :delete, data: { confirm: 'Are you sure?' } %> |
          <% end %>
          <%= link_to 'Back', builds_path %>
          <% if user_signed_in? %>
            <div style="text-align:right">
              <% if current_user.voted_for? @build %>
                <% if current_user.voted_up_on? @build %>
                  <%= link_to 'Unlike', unvote_build_path(@build), method: :delete %>
                <% else %>
                  <%= link_to 'Undislike', undownvote_build_path(@build), method: :delete %>
                <% end %>
              <% else %>
                <%= link_to 'Like', vote_build_path(@build), method: :post %> | 
                <%= link_to 'Dislike', downvote_build_path(@build), method: :post %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>