config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users
  as :user do
    get "signin", to: 'devise/sessions#new'
    delete "signout", to: 'devise/sessions#destroy'
    get 'signup', to: 'devise/registrations#new'
  end

  get 'feed', to: 'feed#show'

  resources :users, only: :show, param: :username do
    member do
      post 'follow', to: 'follows#create'
      delete 'unfollow', to: 'follows#destroy'
    end
  end
  
  resources :mwo_builds do
    member do
      post 'vote', to: 'votes#create_upvote'
      post 'downvote', to: 'votes#create_downvote'
      delete 'unvote', to: 'votes#destroy_upvote'
      delete 'undownvote', to: 'votes#destroy_downvote'
    end
  end

  resources :builds do
    member do
      post 'vote', to: 'votes#create_upvote'
      post 'downvote', to: 'votes#create_downvote'
      delete 'unvote', to: 'votes#destroy_upvote'
      delete 'undownvote', to: 'votes#destroy_downvote'
    end
  end

  resources :tweets
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact-us', to: 'pages#contact_us'
  get 'builds', to: 'builds#index'
  get 'mwo_builds', to: 'mwo_builds#index'
  get 'feed', to: 'feed#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/mwo_build.rb
class MwoBuild < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
  validates :user, presence: true
  validates :mech, presence: true
  validates :url, presence: true

  acts_as_votable
end

app/controllers/mwo_builds_controller.rb
class MwoBuildsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  # GET /mwo_builds
  def index
    @mwo_builds = MwoBuild.all
  end

  # GET /mwo_builds/1
  def show
    @mwo_build = MwoBuild.find(params[:id])
  end

  # GET /mwo_builds/new
  def new
    @mwo_build = current_user.mwo_builds.new
  end

  # GET /mwo_builds/1/edit
  def edit
    @mwo_build = current_user.mwo_builds.find(params[:id])
  end

  # POST /mwo_builds
  def create
    @mwo_build = current_user.mwo_builds.new(mwo_build_params)
    if @mwo_build.save
      redirect_to @mwo_build, notice: 'Mech build was successfully created.'
     else
      render :new
    end
  end

  # PATCH/PUT /mwo_builds/1
  def update
    @mwo_build = current_user.mwo_builds.find(params[:id])
    if @mwo_build.update(mwo_build_params)
      redirect_to @mwo_build, notice: 'Mech build was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /mwo_builds/1
  def destroy
    @mwo_build = current_user.mwo_builds.find(params[:id])
    @mwo_build.destroy
    redirect_to mwo_builds_url, notice: 'Mech build was successfully deleted.'
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def mwo_build_params
      params.require(:mwo_build).permit(:name, :mech, :url, :comments)
    end
end

app/helpers/mwo_builds_helper.rb
module MwoBuildsHelper
end

app/views/mwo_builds/_form.html.erb
<%= form_with(model: mwo_build, local: true) do |form| %>
  <% if mwo_build.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mwo_build.errors.count, "error") %> prohibited this mwo_build from being saved:</h2>

      <ul>
      <% mwo_build.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :mwo_build_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :mech %>
    <%= form.text_field :mech, id: :mwo_build_mech, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :url %>
    <%= form.text_field :url, id: :mwo_build_url, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :comments %>
    <%= form.text_area :comments, id: :mwo_build_comments, class: "form-control" %>
  </div>

 <%= form.submit class: "btn btn-primary" %>
<% end %>

app/views/mwo_builds/edit.html.erb
<div class="container">	
	<h1>Editing Mech Build</h1>

	<%= render 'form', mwo_build: @mwo_build %>

	<%= link_to 'Show', @mwo_build %> |
	<%= link_to 'Back', mwo_builds_path %>
</div>

app/views/mwo_builds/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="card boarder-dark">
        <% if user_signed_in? %>
          <div class="card-body text-dark">
            <h4 class="card-title text-dark">Your Account</h4>
            <% if current_user.avatar.present? %>
              <center><%= image_tag current_user.avatar.url(:medium) %></center>
            <% end %>
            <p class="card-text"><%= current_user.username %></p>
            <p class="card-text"><%= current_user.email %></p>
          </div>
          <div class="card-footer text-primary">
            <a class="card-link"><%= link_to 'Edit your account', user_path(current_user.username) %></a>
         </div>
        <% else %>
          <h6 class="card-text text-dark"><%= link_to "Sign up", signup_path %></h6>
          <h6 class="card-text text-dark"><%= link_to "Sign in", signin_path %></h6>
        <% end %>
      </div>
    </div>
    <div class="col-md-8">  
      <h1>Mechwarrior Online Builds</h1>
      <% if user_signed_in? %>
        <%= link_to 'New Mech Build', new_mwo_build_path %>
      <% end %>
      <ul class="list-group">
        <% @mwo_builds.each do |mwo_build| %>
          <%= link_to mwo_build, class: "list-group-item list-group-item-action list-group-item-light" do %>
            <h5 class="list-group-item-heading text-dark"><strong> Submitted by:</strong> <%= mwo_build.user.username %></h5>
            <p class="list-group-item-text text-dark""><strong>Build Name:</strong> <%= mwo_build.name %></p>
            <p class="list-group-item-text text-dark""><strong>Mech:</strong> <%= mwo_build.mech %></p>
            <p class="list-group-item-text text-dark""><strong>Comments:</strong> <%= mwo_build.comments %></p>
            <p class="list-group-item-text text-dark"">Likes: <%= mwo_build.get_upvotes.size %> | Dislikes: <%= mwo_build.get_downvotes.size %></p>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/mwo_builds/new.html.erb
<div class="container">	
	<h1>New Mech Build</h1>

	<%= render 'form', mwo_build: @mwo_build %>

	<%= link_to 'Back', mwo_builds_path %>
</div>

app/views/mwo_builds/show.html.erb
<div class="container">
  <div class="row">
    <div class="offset-md-2 col-md-8">
      <div class="card boarder-dark">
        <div class="card-body text-dark">
          <h4 class="card-title text-dark"><%= link_to @mwo_build.user.username, user_path(@mwo_build.user.username) %></h4>
            <p class="card-text"><strong>Build Name:</strong> <%= @mwo_build.name %></p>
            <p class="card-text"><strong>Mech:</strong> <%= @mwo_build.mech %></p>
            <p class="card-text"><strong>URL:</strong> <%= link_to(truncate(@mwo_build.url, :length => 140), @mwo_build.url, target: :_blank) %></p>
            <p class="card-text"><strong>Comments:</strong> <%= @mwo_build.comments %></p>
            <p class="card-text">Likes: <%= @mwo_build.get_upvotes.size %> | Dislikes: <%= @mwo_build.get_downvotes.size %></p>
        </div>  
        <div class="card-footer text-primary">
          <%if @mwo_build.user == current_user %>
            <%= link_to 'Edit', edit_mwo_build_path(@mwo_build) %> |
            <%= link_to 'Delete', @mwo_build, method: :delete, data: { confirm: 'Are you sure?' } %> |
          <% end %>
          <%= link_to 'Back', mwo_builds_path %>
          <% if user_signed_in? %>
            <div style="text-align:right">
              <% if current_user.voted_for? @mwo_build %>
                <% if current_user.voted_up_on? @mwo_build %>
                  <%= link_to 'Unlike', unvote_mwo_build_path(@mwo_build), method: :delete %>
                <% else %>
                  <%= link_to 'Undislike', undownvote_mwo_build_path(@mwo_build), method: :delete %>
                <% end %>
              <% else %>
                <%= link_to 'Like', vote_mwo_build_path(@mwo_build), method: :post %> | 
                <%= link_to 'Dislike', downvote_mwo_build_path(@mwo_build), method: :post %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>