config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users
  as :user do
    get "signin", to: 'devise/sessions#new'
    delete "signout", to: 'devise/sessions#destroy'
    get 'signup', to: 'devise/registrations#new'
  end

  get 'feed', to: 'feed#show'

  resources :users, only: :show, param: :username do
    member do
      post 'follow', to: 'follows#create'
      delete 'unfollow', to: 'follows#destroy'
    end
  end
  
  resources :mwo_builds do
    member do
      post 'vote', to: 'votes#create_upvote'
      post 'downvote', to: 'votes#create_downvote'
      delete 'unvote', to: 'votes#destroy_upvote'
      delete 'undownvote', to: 'votes#destroy_downvote'
    end
  end

  resources :builds do
    member do
      post 'vote', to: 'votes#create_upvote'
      post 'downvote', to: 'votes#create_downvote'
      delete 'unvote', to: 'votes#destroy_upvote'
      delete 'undownvote', to: 'votes#destroy_downvote'
    end
  end

  resources :tweets
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact-us', to: 'pages#contact_us'
  get 'builds', to: 'builds#index'
  get 'mwo_builds', to: 'mwo_builds#index'
  get 'feed', to: 'feed#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_authorization.rb
class AdminAuthorization < ActiveAdmin::AuthorizationAdapter

	def authorized?(action, subject = nil)
		user && user.admin?
	end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/build.rb
class Build < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  validates :user, presence: true
  validates :ship, presence: true
  validates :url, presence: true

  acts_as_votable
end

app/models/follow.rb
class Follow < ApplicationRecord

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/mwo_build.rb
class MwoBuild < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
  validates :user, presence: true
  validates :mech, presence: true
  validates :url, presence: true

  acts_as_votable
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  has_many :tweets
  has_many :builds
  has_many :mwo_builds

  validates :username, presence: true, uniqueness: true

  acts_as_followable
  acts_as_follower
  acts_as_voter
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  validates_attachment_size :avatar, less_than: 1.megabytes
end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  # GET /builds
  def index
    @builds = Build.all
  end

  # GET /builds/1
  def show
    @build = Build.find(params[:id])
  end

  # GET /builds/new
  def new
    @build = current_user.builds.new
  end

  # GET /builds/1/edit
  def edit
     @build = current_user.builds.find(params[:id])
  end

  # POST /builds
  def create
    @build = current_user.builds.new(build_params)
    if @build.save
      redirect_to @build, notice: 'Build was successfully created.'
    else
      render :new 
    end
  end

  # PATCH/PUT /builds/1
  def update
    @build = current_user.builds.find(params[:id])
    if @build.update(build_params)
      redirect_to @build, notice: 'Build was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /builds/1
  def destroy
    @build = current_user.builds.find(params[:id])
    @build.destroy
    redirect_to builds_url, notice: 'Build was successfully destroyed.'
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def build_params
      params.require(:build).permit(:ship, :name, :url, :comments)
    end
end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
  before_action :authenticate_user!
  def show
  	@builds = Build.where(user: current_user.all_following)
  	@mwo_builds = MwoBuild.where(user: current_user.all_following)
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :authenticate_user!
  def create
  	user = User.find_by(username: params[:username])
  	Follow.create(followable: user, follower: current_user)
  	redirect_to user_path(user.username), notice: "Successfully followed user"
  end

  def destroy
  	user = User.find_by(username: params[:username])
  	Follow.find_by(followable: user, follower: current_user).destroy
  	redirect_to user_path(user.username), notice: "Successfully unfollowed user"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  # GET /tweets
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  def show
    @tweet = Tweet.find(params[:id])
  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.new
  end

  # GET /tweets/1/edit
  def edit
    @tweet = current_user.tweets.find(params[:id])
  end

  # POST /tweets
  def create
    @tweet = current_user.tweets.new(tweet_params)
    if @tweet.save
      redirect_to @tweet, notice: 'Tweet was successfully created.'
    else
      render :new 
    end
  end

  # PATCH/PUT /tweets/1
  def update
    @tweet = current_user.tweets.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to @tweet, notice: 'Tweet was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tweets/1
  def destroy
    @tweet = current_user.tweets.find(params[:id])
    @tweet.destroy
    redirect_to tweets_url, notice: 'Tweet was successfully destroyed.'
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	def show
    @user = User.find_by(username: params[:username])
    @builds = @user.builds
    @mwo_builds = @user.mwo_builds
  end
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_user!
  def create_upvote
    build = Build.find(params[:id])
    mwo_build = MwoBuild.find(params[:id])
    build.liked_by current_user
    mwo_build.liked_by current_user
    redirect_back(fallback_location: root_path)
  end

   def create_downvote
    build = Build.find(params[:id])
    mwo_build = MwoBuild.find(params[:id])
    build.disliked_by current_user
    mwo_build.disliked_by current_user
    redirect_back(fallback_location: root_path)
  end

  def destroy_upvote
    build = Build.find(params[:id])
    mwo_build = MwoBuild.find(params[:id])
    build.unliked_by current_user
    mwo_build.unliked_by current_user
    redirect_back(fallback_location: root_path)
  end

    def destroy_downvote
    build = Build.find(params[:id])
    mwo_build = MwoBuild.find(params[:id])
    build.undisliked_by current_user
    mwo_build.undisliked_by current_user
    redirect_back(fallback_location: root_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/builds_helper.rb
module BuildsHelper
end

app/helpers/mwo_builds_helper.rb
module MwoBuildsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CHMC Repository</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <div class="container">
        <%= link_to "CHMC Repository", root_path, class: "navbar-brand" %>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Contact", contact_us_path, class: "nav-link" %></li>
        </ul>
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item"><%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "Log out", signout_path, method: :delete, class: "nav-link" %></li>
            <% if current_user.avatar.present? %>
              <li class="round-image-50"><%= image_tag current_user.avatar.url(:thumb) %></li>
            <% end %>
          <%else%>
            <li class="nav-item"><%= link_to "Sign in", signin_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "Sign up", signup_path, class: "btn btn-primary" %></li>
          <%end%>
        </ul>
      </div>
    </nav>

    <!-- Flash Messages -->
    <% flash.each do |name, message| %>
      <%= content_tag(:div, message, class: "alert alert-info #{name}") %>
    <% end %>

    <!-- Page Content -->
    <%= yield %>
    
    <!-- Footer -->
    <footer class="small text-muted">
      <div class="container">
        <center><p> CHMC Respository </p></center>
      </div>
    </footer>

  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>About us</h1>
        <p>This is the repository of builds for members of the Crimson Hydra Mercenary Corporation also known as the Canadian Home Mortgage Company.</p>
    </div>
</div>

app/views/pages/contact_us.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>Contact Us</h1>
        <p>If you require help, please contact me at (Insert Email Here)</a>.</p>
    </div>
</div>

app/views/pages/home.html.erb
<% if user_signed_in? %>
    <div class="jumbotron jumbotron-home">
        <div class="container">
            <h1>Welcome back!</h1>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="col-md-16 col-ed">
                    <h2>Elite Dangerous</h2>
                    <h4>Ship Builds</h4>
                    <p> This is a place for you to store and share the various builds you've created for ships in Elite Dangerous with other people. You can also browse builds other people have created as well. </p>
                    <p><%= link_to "Ship Builds", builds_path, class: "btn btn-secondary" %></p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="col-md-16 col-mwo">
                    <h2>Mechwarrior Online</h2>
                    <h4>Mech Builds </h4>
                    <p> This is a place for you to store and share the various builds you've created for mechs in Mechwarrior Online with other people. You can also browse builds other people have created as well.  </p>
                    <p><%= link_to "Mech Builds", mwo_builds_path, class: "btn btn-secondary" %></p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="col-md-16 col-feed">
                    <h2>Your Feed</h2>
                    <h4>Elite Dangerous and MWO Builds</h4>
                    <p>This is where you can see all of the builds submitted by people you have followed. Get the latest and most dangerous builds by your favorite content creators.</p>
                    <p><%= link_to "My Feed", feed_path, class: "btn btn-secondary" %></p>
                </div>
            </div>
<% else %>
    <div class="jumbotron jumbotron-home">
        <div class="container">
            <h1>Welcome to our website!</h1>
            <p>This is a repository for CHMC's various builds on various video games.</p>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="col-md-16 col-ed">
                    <h2>Elite Dangerous</h2>
                    <h4>Ship Builds</h4>
                    <p> This is a place for you to store and share the various builds you've created for ships in Elite Dangerous with other people. You can also browse builds other people have created as well. </p>
                    <p><%= link_to "Ship Builds", builds_path, class: "btn btn-secondary disabled" %> Sign in to see ship builds.</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="col-md-16 col-mwo">
                    <h2>Mechwarrior Online</h2>
                    <h4>Mech Builds </h4>
                    <p> This is a place for you to store and share the various builds you've created for mechs in Mechwarrior Online with other people. You can also browse builds other people have created as well.  </p>
                    <p><%= link_to "Mech Builds", mwo_builds_path, class: "btn btn-secondary disabled" %> Sign in to see mech builds.</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="col-md-16 col-feed">
                    <h2>Your Feed</h2>
                    <h4>Elite Dangerous and MWO Builds</h4>
                    <p>This is where you can see all of the builds submitted by people you have followed. Get the latest and most dangerous builds by your favorite content creators.</p>
                    <p><%= link_to "My Feed", feed_path, class: "btn btn-secondary disabled" %> Sign in to see your feed</p>
                </div>
            </div>
        </div>
    </div>
<% end %>